# This file was generated by GoReleaser. DO NOT EDIT.
cask "aasdd-cli" do
  name "aasdd-cli"
  desc "AASDD CLI — verify and scaffold AASDD specs"
  homepage "https://github.com/smithyai/aasdd-cli"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aasdd-cli"

  on_macos do
    on_intel do
      url "https://github.com/smithyai/aasdd-cli/releases/download/v#{version}/aasdd-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "7030d5b186cb6f35eab258a62414299c6daa99e43f0bb869f8af9732b24f5a2d"
    end
    on_arm do
      url "https://github.com/smithyai/aasdd-cli/releases/download/v#{version}/aasdd-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "d06e767c7e54e04ebf74d23fbc440f07f61a8d751d2bec2fb0aabb3860db437e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/smithyai/aasdd-cli/releases/download/v#{version}/aasdd-cli_#{version}_linux_amd64.tar.gz"
      sha256 "3b10843754ebd45b5b135ff67c48436bab6c8cdff4cb1f055ec0b1a499fab15c"
    end
    on_arm do
      url "https://github.com/smithyai/aasdd-cli/releases/download/v#{version}/aasdd-cli_#{version}_linux_arm64.tar.gz"
      sha256 "83dddc90e5a6dcafffdc1206100a3f1ae1cbbf31b7257d742c08f53ff1a6d59f"
    end
  end

  # No zap stanza required
end
